### ISSUE TITLE
What size problems have you tested this on?

### ISSUE THREAD

**Issue by pst2154** [smuecke/qubolite#3]
Have you tried thousands of variables?

**Comment by pst2154** [comment]
Ok I just tested this, the SA works great. It found a better solution fast than CPLEX could find pretty quickly for a ~700 variable problem.

**Comment by smuecke** [comment]
Cool, I'm glad it works for you! – I think you'll run into space problems for _very_ large problem instances (like several thousand to millions), because, by design, this library just wraps around numpy matrices. I haven't tested it thoroughly on such large instances.
